title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal

domain: map-ad.github.io
url: https://map-ad.github.io
baseurl: /REPOSITORY-NAME/docs
