title: MAP Tools Docs
logo: /assets/img/MAP-logo.jpg
logo_footer: /assets/img/UKDRI_logo.jpg
description: Documentation for the tools used in the Multi-'omics Atlas Project (MAP)'
theme: jekyll-theme-minimal

domain: map-ad.github.io
url: https://map-ad.github.io
baseurl: ""
