title: MAP Tools Docs
description: Documentation for the tools used in the Multi-'omics Atlas Project (MAP)'
theme: jekyll-theme-minimal
authour: MAP Team

domain: map-ad.github.io
url: https://map-ad.github.io
baseurl: ""

plugins:
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'